# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'petrack' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for petrack
  pod 'GoogleMaps'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'petrackTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'petrack-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for petrack-tvOS

  target 'petrack-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
