# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'petrack' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for petrack
  pod 'GoogleMaps'

  
  #All Link From Native Project 
  #pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  #pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk' //use FacebookSDK on xcode project
  #pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  #pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  #pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  #pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  #pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  target 'petrackTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'petrack-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for petrack-tvOS

  target 'petrack-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
